name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2

      - name: Run linter
        run: deno lint --allow-dirty

      - name: Run tests
        run: deno test

      - name: Publish package
        run: npx jsr publish
